server:
  port: 8000
spring:
  datasource:
    username: root
    password: xingbo
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/tourism?useSSL=false&serverTimezone=UTC
mybatis:
  configuration:
    map-underscore-to-camel-case: true
